// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LastTriggerHandlerFunc turns a function with the right signature into a last trigger handler
type LastTriggerHandlerFunc func(LastTriggerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn LastTriggerHandlerFunc) Handle(params LastTriggerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// LastTriggerHandler interface for that can handle valid last trigger params
type LastTriggerHandler interface {
	Handle(LastTriggerParams, interface{}) middleware.Responder
}

// NewLastTrigger creates a new http.Handler for the last trigger operation
func NewLastTrigger(ctx *middleware.Context, handler LastTriggerHandler) *LastTrigger {
	return &LastTrigger{Context: ctx, Handler: handler}
}

/*LastTrigger swagger:route GET /projects/{project_name_or_id}/webhook/lasttrigger webhook lastTrigger

Get project webhook policy last trigger info

This endpoint returns last trigger information of project webhook policy.


*/
type LastTrigger struct {
	Context *middleware.Context
	Handler LastTriggerHandler
}

func (o *LastTrigger) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLastTriggerParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
