// Code generated by go-swagger; DO NOT EDIT.

package project_metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateProjectMetadataHandlerFunc turns a function with the right signature into a update project metadata handler
type UpdateProjectMetadataHandlerFunc func(UpdateProjectMetadataParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateProjectMetadataHandlerFunc) Handle(params UpdateProjectMetadataParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateProjectMetadataHandler interface for that can handle valid update project metadata params
type UpdateProjectMetadataHandler interface {
	Handle(UpdateProjectMetadataParams, interface{}) middleware.Responder
}

// NewUpdateProjectMetadata creates a new http.Handler for the update project metadata operation
func NewUpdateProjectMetadata(ctx *middleware.Context, handler UpdateProjectMetadataHandler) *UpdateProjectMetadata {
	return &UpdateProjectMetadata{Context: ctx, Handler: handler}
}

/*UpdateProjectMetadata swagger:route PUT /projects/{project_name_or_id}/metadatas/{meta_name} projectMetadata updateProjectMetadata

Update the specific metadata for the specific project

Update the specific metadata for the specific project

*/
type UpdateProjectMetadata struct {
	Context *middleware.Context
	Handler UpdateProjectMetadataHandler
}

func (o *UpdateProjectMetadata) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateProjectMetadataParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
