// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateProjectMemberHandlerFunc turns a function with the right signature into a update project member handler
type UpdateProjectMemberHandlerFunc func(UpdateProjectMemberParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateProjectMemberHandlerFunc) Handle(params UpdateProjectMemberParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateProjectMemberHandler interface for that can handle valid update project member params
type UpdateProjectMemberHandler interface {
	Handle(UpdateProjectMemberParams, interface{}) middleware.Responder
}

// NewUpdateProjectMember creates a new http.Handler for the update project member operation
func NewUpdateProjectMember(ctx *middleware.Context, handler UpdateProjectMemberHandler) *UpdateProjectMember {
	return &UpdateProjectMember{Context: ctx, Handler: handler}
}

/*UpdateProjectMember swagger:route PUT /projects/{project_name_or_id}/members/{mid} member updateProjectMember

Update project member

Update project member relationship

*/
type UpdateProjectMember struct {
	Context *middleware.Context
	Handler UpdateProjectMemberHandler
}

func (o *UpdateProjectMember) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateProjectMemberParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
