// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SearchUsersHandlerFunc turns a function with the right signature into a search users handler
type SearchUsersHandlerFunc func(SearchUsersParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SearchUsersHandlerFunc) Handle(params SearchUsersParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SearchUsersHandler interface for that can handle valid search users params
type SearchUsersHandler interface {
	Handle(SearchUsersParams, interface{}) middleware.Responder
}

// NewSearchUsers creates a new http.Handler for the search users operation
func NewSearchUsers(ctx *middleware.Context, handler SearchUsersHandler) *SearchUsers {
	return &SearchUsers{Context: ctx, Handler: handler}
}

/*SearchUsers swagger:route GET /users/search user searchUsers

Search users by username

This endpoint is to search the users by username.  It's open for all authenticated requests.


*/
type SearchUsers struct {
	Context *middleware.Context
	Handler SearchUsersHandler
}

func (o *SearchUsers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSearchUsersParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
