// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SetUserSysAdminHandlerFunc turns a function with the right signature into a set user sys admin handler
type SetUserSysAdminHandlerFunc func(SetUserSysAdminParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SetUserSysAdminHandlerFunc) Handle(params SetUserSysAdminParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SetUserSysAdminHandler interface for that can handle valid set user sys admin params
type SetUserSysAdminHandler interface {
	Handle(SetUserSysAdminParams, interface{}) middleware.Responder
}

// NewSetUserSysAdmin creates a new http.Handler for the set user sys admin operation
func NewSetUserSysAdmin(ctx *middleware.Context, handler SetUserSysAdminHandler) *SetUserSysAdmin {
	return &SetUserSysAdmin{Context: ctx, Handler: handler}
}

/*SetUserSysAdmin swagger:route PUT /users/{user_id}/sysadmin user setUserSysAdmin

Update a registered user to change to be an administrator of Harbor.

*/
type SetUserSysAdmin struct {
	Context *middleware.Context
	Handler SetUserSysAdminHandler
}

func (o *SetUserSysAdmin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSetUserSysAdminParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
