// Code generated by go-swagger; DO NOT EDIT.

package usergroup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteUserGroupHandlerFunc turns a function with the right signature into a delete user group handler
type DeleteUserGroupHandlerFunc func(DeleteUserGroupParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteUserGroupHandlerFunc) Handle(params DeleteUserGroupParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteUserGroupHandler interface for that can handle valid delete user group params
type DeleteUserGroupHandler interface {
	Handle(DeleteUserGroupParams, interface{}) middleware.Responder
}

// NewDeleteUserGroup creates a new http.Handler for the delete user group operation
func NewDeleteUserGroup(ctx *middleware.Context, handler DeleteUserGroupHandler) *DeleteUserGroup {
	return &DeleteUserGroup{Context: ctx, Handler: handler}
}

/*DeleteUserGroup swagger:route DELETE /usergroups/{group_id} usergroup deleteUserGroup

Delete user group

Delete user group

*/
type DeleteUserGroup struct {
	Context *middleware.Context
	Handler DeleteUserGroupHandler
}

func (o *DeleteUserGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteUserGroupParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
