// Code generated by go-swagger; DO NOT EDIT.

package replication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetReplicationExecutionHandlerFunc turns a function with the right signature into a get replication execution handler
type GetReplicationExecutionHandlerFunc func(GetReplicationExecutionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReplicationExecutionHandlerFunc) Handle(params GetReplicationExecutionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetReplicationExecutionHandler interface for that can handle valid get replication execution params
type GetReplicationExecutionHandler interface {
	Handle(GetReplicationExecutionParams, interface{}) middleware.Responder
}

// NewGetReplicationExecution creates a new http.Handler for the get replication execution operation
func NewGetReplicationExecution(ctx *middleware.Context, handler GetReplicationExecutionHandler) *GetReplicationExecution {
	return &GetReplicationExecution{Context: ctx, Handler: handler}
}

/*GetReplicationExecution swagger:route GET /replication/executions/{id} replication getReplicationExecution

Get the specific replication execution

Get the replication execution specified by ID

*/
type GetReplicationExecution struct {
	Context *middleware.Context
	Handler GetReplicationExecutionHandler
}

func (o *GetReplicationExecution) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReplicationExecutionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
