// Code generated by go-swagger; DO NOT EDIT.

package scanner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListScannersHandlerFunc turns a function with the right signature into a list scanners handler
type ListScannersHandlerFunc func(ListScannersParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListScannersHandlerFunc) Handle(params ListScannersParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListScannersHandler interface for that can handle valid list scanners params
type ListScannersHandler interface {
	Handle(ListScannersParams, interface{}) middleware.Responder
}

// NewListScanners creates a new http.Handler for the list scanners operation
func NewListScanners(ctx *middleware.Context, handler ListScannersHandler) *ListScanners {
	return &ListScanners{Context: ctx, Handler: handler}
}

/*ListScanners swagger:route GET /scanners scanner listScanners

List scanner registrations

Returns a list of currently configured scanner registrations.


*/
type ListScanners struct {
	Context *middleware.Context
	Handler ListScannersHandler
}

func (o *ListScanners) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListScannersParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
