// Code generated by go-swagger; DO NOT EDIT.

package preheat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetExecutionParams creates a new GetExecutionParams object
// no default values defined in spec.
func NewGetExecutionParams() GetExecutionParams {

	return GetExecutionParams{}
}

// GetExecutionParams contains all the bound params for the get execution operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetExecution
type GetExecutionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*An unique ID for the request
	  Min Length: 1
	  In: header
	*/
	XRequestID *string
	/*Execution ID
	  Required: true
	  In: path
	*/
	ExecutionID int64
	/*Preheat Policy Name
	  Required: true
	  In: path
	*/
	PreheatPolicyName string
	/*The name of the project
	  Required: true
	  In: path
	*/
	ProjectName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetExecutionParams() beforehand.
func (o *GetExecutionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindXRequestID(r.Header[http.CanonicalHeaderKey("X-Request-Id")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rExecutionID, rhkExecutionID, _ := route.Params.GetOK("execution_id")
	if err := o.bindExecutionID(rExecutionID, rhkExecutionID, route.Formats); err != nil {
		res = append(res, err)
	}

	rPreheatPolicyName, rhkPreheatPolicyName, _ := route.Params.GetOK("preheat_policy_name")
	if err := o.bindPreheatPolicyName(rPreheatPolicyName, rhkPreheatPolicyName, route.Formats); err != nil {
		res = append(res, err)
	}

	rProjectName, rhkProjectName, _ := route.Params.GetOK("project_name")
	if err := o.bindProjectName(rProjectName, rhkProjectName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindXRequestID binds and validates parameter XRequestID from header.
func (o *GetExecutionParams) bindXRequestID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XRequestID = &raw

	if err := o.validateXRequestID(formats); err != nil {
		return err
	}

	return nil
}

// validateXRequestID carries on validations for parameter XRequestID
func (o *GetExecutionParams) validateXRequestID(formats strfmt.Registry) error {

	if err := validate.MinLength("X-Request-Id", "header", (*o.XRequestID), 1); err != nil {
		return err
	}

	return nil
}

// bindExecutionID binds and validates parameter ExecutionID from path.
func (o *GetExecutionParams) bindExecutionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("execution_id", "path", "int64", raw)
	}
	o.ExecutionID = value

	return nil
}

// bindPreheatPolicyName binds and validates parameter PreheatPolicyName from path.
func (o *GetExecutionParams) bindPreheatPolicyName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.PreheatPolicyName = raw

	return nil
}

// bindProjectName binds and validates parameter ProjectName from path.
func (o *GetExecutionParams) bindProjectName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ProjectName = raw

	return nil
}
