// Code generated by go-swagger; DO NOT EDIT.

package preheat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPreheatLogHandlerFunc turns a function with the right signature into a get preheat log handler
type GetPreheatLogHandlerFunc func(GetPreheatLogParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPreheatLogHandlerFunc) Handle(params GetPreheatLogParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetPreheatLogHandler interface for that can handle valid get preheat log params
type GetPreheatLogHandler interface {
	Handle(GetPreheatLogParams, interface{}) middleware.Responder
}

// NewGetPreheatLog creates a new http.Handler for the get preheat log operation
func NewGetPreheatLog(ctx *middleware.Context, handler GetPreheatLogHandler) *GetPreheatLog {
	return &GetPreheatLog{Context: ctx, Handler: handler}
}

/*GetPreheatLog swagger:route GET /projects/{project_name}/preheat/policies/{preheat_policy_name}/executions/{execution_id}/tasks/{task_id}/logs preheat getPreheatLog

Get the log text stream of the specified task for the given execution

Get the log text stream of the specified task for the given execution

*/
type GetPreheatLog struct {
	Context *middleware.Context
	Handler GetPreheatLogHandler
}

func (o *GetPreheatLog) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPreheatLogParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
