// Code generated by go-swagger; DO NOT EDIT.

package preheat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListInstancesHandlerFunc turns a function with the right signature into a list instances handler
type ListInstancesHandlerFunc func(ListInstancesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListInstancesHandlerFunc) Handle(params ListInstancesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListInstancesHandler interface for that can handle valid list instances params
type ListInstancesHandler interface {
	Handle(ListInstancesParams, interface{}) middleware.Responder
}

// NewListInstances creates a new http.Handler for the list instances operation
func NewListInstances(ctx *middleware.Context, handler ListInstancesHandler) *ListInstances {
	return &ListInstances{Context: ctx, Handler: handler}
}

/*ListInstances swagger:route GET /p2p/preheat/instances preheat listInstances

List P2P provider instances

List P2P provider instances

*/
type ListInstances struct {
	Context *middleware.Context
	Handler ListInstancesHandler
}

func (o *ListInstances) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListInstancesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
