// Code generated by go-swagger; DO NOT EDIT.

package preheat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/goharbor/harbor/src/server/v2.0/models"
)

// NewStopExecutionParams creates a new StopExecutionParams object
// no default values defined in spec.
func NewStopExecutionParams() StopExecutionParams {

	return StopExecutionParams{}
}

// StopExecutionParams contains all the bound params for the stop execution operation
// typically these are obtained from a http.Request
//
// swagger:parameters StopExecution
type StopExecutionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*An unique ID for the request
	  Min Length: 1
	  In: header
	*/
	XRequestID *string
	/*The data of execution
	  Required: true
	  In: body
	*/
	Execution *models.Execution
	/*Execution ID
	  Required: true
	  In: path
	*/
	ExecutionID int64
	/*Preheat Policy Name
	  Required: true
	  In: path
	*/
	PreheatPolicyName string
	/*The name of the project
	  Required: true
	  In: path
	*/
	ProjectName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewStopExecutionParams() beforehand.
func (o *StopExecutionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindXRequestID(r.Header[http.CanonicalHeaderKey("X-Request-Id")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Execution
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("execution", "body", ""))
			} else {
				res = append(res, errors.NewParseError("execution", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Execution = &body
			}
		}
	} else {
		res = append(res, errors.Required("execution", "body", ""))
	}
	rExecutionID, rhkExecutionID, _ := route.Params.GetOK("execution_id")
	if err := o.bindExecutionID(rExecutionID, rhkExecutionID, route.Formats); err != nil {
		res = append(res, err)
	}

	rPreheatPolicyName, rhkPreheatPolicyName, _ := route.Params.GetOK("preheat_policy_name")
	if err := o.bindPreheatPolicyName(rPreheatPolicyName, rhkPreheatPolicyName, route.Formats); err != nil {
		res = append(res, err)
	}

	rProjectName, rhkProjectName, _ := route.Params.GetOK("project_name")
	if err := o.bindProjectName(rProjectName, rhkProjectName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindXRequestID binds and validates parameter XRequestID from header.
func (o *StopExecutionParams) bindXRequestID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XRequestID = &raw

	if err := o.validateXRequestID(formats); err != nil {
		return err
	}

	return nil
}

// validateXRequestID carries on validations for parameter XRequestID
func (o *StopExecutionParams) validateXRequestID(formats strfmt.Registry) error {

	if err := validate.MinLength("X-Request-Id", "header", (*o.XRequestID), 1); err != nil {
		return err
	}

	return nil
}

// bindExecutionID binds and validates parameter ExecutionID from path.
func (o *StopExecutionParams) bindExecutionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("execution_id", "path", "int64", raw)
	}
	o.ExecutionID = value

	return nil
}

// bindPreheatPolicyName binds and validates parameter PreheatPolicyName from path.
func (o *StopExecutionParams) bindPreheatPolicyName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.PreheatPolicyName = raw

	return nil
}

// bindProjectName binds and validates parameter ProjectName from path.
func (o *StopExecutionParams) bindProjectName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ProjectName = raw

	return nil
}
