// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetProjectDeletableHandlerFunc turns a function with the right signature into a get project deletable handler
type GetProjectDeletableHandlerFunc func(GetProjectDeletableParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProjectDeletableHandlerFunc) Handle(params GetProjectDeletableParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetProjectDeletableHandler interface for that can handle valid get project deletable params
type GetProjectDeletableHandler interface {
	Handle(GetProjectDeletableParams, interface{}) middleware.Responder
}

// NewGetProjectDeletable creates a new http.Handler for the get project deletable operation
func NewGetProjectDeletable(ctx *middleware.Context, handler GetProjectDeletableHandler) *GetProjectDeletable {
	return &GetProjectDeletable{Context: ctx, Handler: handler}
}

/*GetProjectDeletable swagger:route GET /projects/{project_name_or_id}/_deletable project getProjectDeletable

Get the deletable status of the project

Get the deletable status of the project

*/
type GetProjectDeletable struct {
	Context *middleware.Context
	Handler GetProjectDeletableHandler
}

func (o *GetProjectDeletable) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetProjectDeletableParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
