// Code generated by go-swagger; DO NOT EDIT.

package robotv1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateRobotV1HandlerFunc turns a function with the right signature into a create robot v1 handler
type CreateRobotV1HandlerFunc func(CreateRobotV1Params, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateRobotV1HandlerFunc) Handle(params CreateRobotV1Params, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateRobotV1Handler interface for that can handle valid create robot v1 params
type CreateRobotV1Handler interface {
	Handle(CreateRobotV1Params, interface{}) middleware.Responder
}

// NewCreateRobotV1 creates a new http.Handler for the create robot v1 operation
func NewCreateRobotV1(ctx *middleware.Context, handler CreateRobotV1Handler) *CreateRobotV1 {
	return &CreateRobotV1{Context: ctx, Handler: handler}
}

/*CreateRobotV1 swagger:route POST /projects/{project_name_or_id}/robots robotv1 createRobotV1

Create a robot account

Create a robot account

*/
type CreateRobotV1 struct {
	Context *middleware.Context
	Handler CreateRobotV1Handler
}

func (o *CreateRobotV1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateRobotV1Params()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
